sudo: true
dist: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: AbHf2bOBc3VeaP56JkK7bNSp7zaQ0SrVAf6j1blQb7reqa6RMdDGFPmcjMI/gMLaaJ4FWPNseK9n7s7Q5cHkjjbUOEFqGxN1uXJ2QQfIuomrDEKKaUG9IC7dTLxooZ3P5Sb445vAoM9Ep9ILEm4krpR3iA/DJG7BDdAMHzID3bLB7Qdlm76Syifo0Gxvw1pCQ0NvrDOsT0zef+hvKCjQMs08EdwcAhM8uczsTzTH/tBW51auDWOGGcEXQUGfUiATol0jWZ5DhKXGSev1IXUl7Wy055exffbr1tIGa8OfMolixRmcJjguDLJYjCeJNg9iPBb+S6RpNiBXQY+Kt3SfM4tvBxTIcT4ohEk6EgNKsBzFNDglzJUxnvmkJfLGmqEDX5w/VyKDE9xKA8Inuc2Uq7iD5q13ToHO+JAvBfXLP4JHddRO+n+MSW6VpHsmwmWg74r9A4nbcqWxWC7g6GAADiGvUBfyky6hgftEC7PZ826DfHI5TUBiaa41wMZv69pVLqTgFUCzNzbRj9QWwXkQ2sdY3qfffXqC4b6Ugzer6q6TaiOjgF2cymv9qi1JaiVT52LWKWzMEEuNMpBH6lYAuRBlLDd1zSVbimL17MRmcwyyNtMhvrJwewivfYhDSNAMndcnKGn2KLYdnfLsiroCLJREGUmtgwiIBLVsZuP9uxI=
  - secure: pg+VHLl8Eu8t4ipy5F+065kwW+tJzXGAUqE2pwaKKyZVAgOd1bv3UbNS7C4koKLu31uj5b6ZdvJKHGZTfJ6kDXS9gmOsmDzSlz1TEYLKOy9MdxwEjHYnI0SR+okGfv9VjsgTKvIQTcmdZB2a2XIMxMmxP6exdf/fAkQhm3FOX00OuV5c9q/YSb02y3v8eHLBKLHYNnzMDh5kykUxAdQ+r2bKKHFNEfIWv5obMWcGsWSAQ0LcnqcGAainjn1rwjA2/JnLGymNz3K8vC2WHxqDQr8vBjablUusuUHsTMOiCgyDQLHxaDZtJfX4btBA1TV1Ub1s1yPCJKPn4E94Ug7bADwD5zhresIOakhY2vycqFujaLtangoV14RYWDrOVS2QoTbmPzYOx6HK5IJbw3+U6EQ7O0u/4txx4APyiAIn0JQyncYSHLjyzbs0bZbxt1NY0cAYU30FvvfbdU4vg3eK0sJwRwCDFRQBsJYtmuFqXb+k5GzoJR0DajJ8uE8pVsbVVqsfnpNFB3R45xbSmDxmDDPvbdQXPIcKP0fHkncfCx7V33W7K24LBUUN0RyIQFFN5Xe6FJWRL0tmXTuQrB6gvtheMDBlPux2JpwVz4oaTHQ5yqN3JlCPF8wg9Iupu/vCZWdTZXFDtgap6wju5w5wmhp5C3z9FtmuvFGpVJBrxCM=
  - secure: QS8efCBTVEB+MDzjFDVdqNuRN9qTIgnsI48uU3Woap4RFxLzal/2JkG3v04ZYuc7Zp/m4CgUTa9JSCQB5QQ+7E2pXVlRfY91tcjVqvXQG6n7lT5EIbSMiCbIrifD5iZtv/E4wIbSEulEnWAQ7P8frXPQ19TAuqwS/aMyK6aGbbff8F4gD7T2F5TFPl+P5SF7XDfiHqAuprSzmZUDRTkiti34tCPV02pkkd1aqGokFTpPaW2YM7GaJdAX6SVftJhLPTbrIL/vc+zq5NjZnQyWTxRTD4Pn53i/9aQHIy+6zcsvko7jqbl8PtDzRbvUuxB+CTAdIlWtg241K5TaWFznWF1S7cRzRmE6EUYtUFkPczkERTuJnFDW+3fWt/RgzxtnE6ACR61pq0TMXXm4bwzzDU5f8jp07NCtYF0ERT0LxzNLOLygQ4Vyx58dm5HYMR44XHg3d/mktLLGTO7Hnh8Tsg24FGpEBnSG5a+/NuZP0Nx0DUMEhhK9A6lHOiwNo9khyFCjBSKyRNwkJb3AWbuFXYgn/uTgLOgXDa8ZToHySraKzyRzBiDSP08tpnBfWREanzfmksTETLR3HGyZrtcjEI4oBVYjWEA7ImXQ2HMjOGnq1jHvpiWwgSP+Y79k2ObYkXZ8PW9F+MnwoUm1BBiDCv/Or3qfOzW+PK0+/zjupPY=
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in assets/server.key.enc -out assets/server.key
  -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DevHub
script:
- sfdx force:org:create -v DevHub -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
